[package]
name = "ten-armed-bandit-rs"
version = "0.1.0"
authors = ["qucumbah <sc.buher@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
rand_distr = "0.4.0"
